#!/bin/bash

cd /sys/kernel/config/usb_gadget
mkdir -p my_gadget
cd my_gadget

# These are the details for immitating Google Chromecast Remote
echo 0x0957 > idVendor
echo 0x0001 > idProduct
# These are the generic buttons and should be used
#echo 0x1d6b > idVendor
#echo 0x0104 > idProduct



mkdir -p strings/0x409
echo "deadbeefdeadbeef" > strings/0x409/serialnumber
echo "foxy82" > strings/0x409/manufacturer
echo "Wifi USB HID" > strings/0x409/product

mkdir -p configs/c.1/
echo 250 > configs/c.1/MaxPower

# KEYBOARD (hidg0)
mkdir -p functions/hid.g1
echo 1 > functions/hid.g1/protocol
echo 1 > functions/hid.g1/subclass
echo 8 > functions/hid.g1/report_length
echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.g1/report_desc

# Consumer control (hidg1)
# TODO add System Control in
mkdir -p functions/hid.g2
echo 0 > functions/hid.g2/protocol
echo 0 > functions/hid.g2/subclass
echo 1 > functions/hid.g2/report_length
echo -ne \\x05\\x0C\\x09\\x01\\xA1\\x01\\x75\\x10\\x95\\x01\\x15\\x00\\x26\\xFF\\x03\\x19\\x00\\x2A\\xFF\\x03\\x81\\x00\\xC0 > functions/hid.g2/report_desc

# MOUSE (hidg2) RELATIVE ((report ID 1) / ABS (report ID 2)
mkdir -p functions/hid.g3
echo 2 > functions/hid.g3/protocol
echo 1 > functions/hid.g3/subclass
echo 6 > functions/hid.g3/report_length
echo -ne \\x05\\x01\\x09\\x02\\xa1\\x01\\x09\\x01\\xa1\\x00\\x85\\x01\\x05\\x09\\x19\\x01\\x29\\x03\\x15\\x00\\x25\\x01\\x95\\x03\\x75\\x01\\x81\\x02\\x95\\x01\\x75\\x05\\x81\\x03\\x05\\x01\\x09\\x30\\x09\\x31\\x15\\x81\\x25\\x7f\\x75\\x08\\x95\\x02\\x81\\x06\\x95\\x02\\x75\\x08\\x81\\x01\\xc0\\xc0\\x05\\x01\\x09\\x02\\xa1\\x01\\x09\\x01\\xa1\\x00\\x85\\x02\\x05\\x09\\x19\\x01\\x29\\x03\\x15\\x00\\x25\\x01\\x95\\x03\\x75\\x01\\x81\\x02\\x95\\x01\\x75\\x05\\x81\\x01\\x05\\x01\\x09\\x30\\x09\\x31\\x15\\x00\\x26\\xff\\x7f\\x95\\x02\\x75\\x10\\x81\\x02\\xc0\\xc0 > functions/hid.g3/report_desc

ln -s functions/hid.g1 configs/c.1/
ln -s functions/hid.g2 configs/c.1/
ln -s functions/hid.g3 configs/c.1/

ls /sys/class/udc > UDC
chmod 777 /dev/hidg0
chmod 777 /dev/hidg1
chmod 777 /dev/hidg2
